name: Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start Application
        run: |
          echo "Starting the application..."
          npm start &
          echo $! > application_pid.txt
          sleep 10

      - name: Wait for Web Service to be fully ready
        run: |
          echo "Waiting for the web service to fully start..."
          until [ $(curl -s -o /dev/null -w '%{http_code}' http://localhost:3000) -eq 200 ]; do
            echo "Web service is not ready yet..."
            sleep 10
          done
          echo "Web service is ready."

      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Stop Application
        run: |
          kill $(cat application_pid.txt)
