name: Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:20
        ports:
          - 3000:3000
        options: --health-cmd="curl --fail http://localhost:3000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=50
        env:
          PORT: 3000
        volumes:
          - .:/workspace

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: /workspace

      - name: Start Application
        run: npm start &
        working-directory: /workspace

      - name: Wait for Web Service to be fully ready
        run: |
          echo "Waiting for the web service to fully start..."
          until [[ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3000)" == "200" ]]; do
            echo "Web service is not ready yet..."
            sleep 10
          done
          echo "Web service is ready."

      - name: Print Docker Logs
        run: docker logs $(docker ps -q -f "ancestor=node:20")

      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:3000
        working-directory: /workspace
